name: ✅ Test
on:
  push:
jobs:
  test:
    strategy:
      matrix:
        os: [[🐧, Ubuntu], [🍎, macOS], [🪟, Windows]]
    name: ${{ matrix.os[0] }} Test ${{ matrix.os[1] }}
    runs-on: ${{ matrix.os[1] }}-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
      - name: Generate Matrix
        id: matrix
        uses: ./
      - name: Show Result
        run: echo '${{ steps.matrix.outputs.matrix }}'
